spring:
  datasource:
    url: jdbc:h2:~/springdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap2020
    password: fiap2020
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
file:
  path: classpath:alunos_carga_inicial.txt